[ConfigDatabase]
Category = "MONGO"
ReplicaType = "MASTER"
Server = "mongodb://127.0.0.1:27017"
#Server = "192.168.1.1"
#Port = 27017
#ConnectionMax = 5000
#Enable = true

#[ConfigRedis]
#Id = 1
#Name = "Global"
#Server = "172.16.13.183:6379"